"use client";
import { useState } from "react";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import type { Member } from "@/lib/types";
export function QuickExpenseForm({ tripId, members, userId, onDone }: { tripId: string; members: Member[]; userId: string; onDone: () => void }) {
  const [saving, setSaving] = useState(false), [error, setError] = useState(""), [splitEqually, setSplitEqually] = useState(false), [selected, setSelected] = useState<string[]>(members.map(member => member.uid));
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const amount = Math.round(Number(form.get("amount")) * 100); const participants = splitEqually ? members.filter(member => selected.includes(member.uid)) : members.filter(member => member.uid === userId); if (amount <= 0 || !participants.length) { setError("Enter an amount and select at least one member."); return; } const base = Math.floor(amount / participants.length), remainder = amount % participants.length; setSaving(true); try { await addDoc(collection(db, "trips", tripId, "expenses"), { title: form.get("title"), amount, date: new Date(String(form.get("date"))), notes: "", splitType: "equal", participants: participants.map((member, index) => ({ uid: member.uid, amount: base + (index < remainder ? 1 : 0) })), payments: [{ uid: userId, amount }], createdBy: userId, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); onDone(); } catch { setError("Could not save this expense. Please try again."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="card mt-4 grid gap-3">{error && <p className="text-red-700">{error}</p>}<label><span className="label">Expense name</span><input className="field" name="title" required placeholder="Dinner" /></label><label><span className="label">Amount</span><input className="field" name="amount" type="number" min="0.01" step="0.01" required /></label><label><span className="label">Date</span><input className="field" type="date" name="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={splitEqually} onChange={event => setSplitEqually(event.target.checked)} />Split equally with members</label>{splitEqually && <fieldset><legend className="label">Select members</legend><div className="grid gap-2">{members.map(member => <label className="flex items-center gap-2" key={member.uid}><input type="checkbox" checked={selected.includes(member.uid)} onChange={() => setSelected(value => value.includes(member.uid) ? value.filter(uid => uid !== member.uid) : [...value, member.uid])} />{member.name}</label>)}</div></fieldset>}<p className="text-sm muted">You pay this expense. When selected, the total is divided equally among the chosen members.</p><button className="btn" disabled={saving}>{saving ? "Saving…" : "Save expense"}</button></form>;
}
