"use client";
import { useState } from "react";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import type { Member } from "@/lib/types";
export function QuickExpenseForm({ tripId, members, userId, onDone }: { tripId: string; members: Member[]; userId: string; onDone: () => void }) {
const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const amount = Math.round(Number(form.get("amount")) * 100); if (amount <= 0 || !members.length) { setError("Enter an amount greater than zero."); return; } const base = Math.floor(amount / members.length), remainder = amount % members.length; setSaving(true); try { await addDoc(collection(db, "trips", tripId, "expenses"), { title: form.get("title"), amount, date: new Date(String(form.get("date"))), notes: "", splitType: "equal", participants: members.map((member, index) => ({ uid: member.uid, amount: base + (index < remainder ? 1 : 0) })), payments: [{ uid: userId, amount }], createdBy: userId, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); onDone(); } catch { setError("Could not save this expense. Please try again."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="card mt-4 grid gap-3">{error && <p className="text-red-700">{error}</p>}<label><span className="label">Expense name</span><input className="field" name="title" required placeholder="Dinner" /></label><label><span className="label">Amount</span><input className="field" name="amount" type="number" min="0.01" step="0.01" required /></label><label><span className="label">Date</span><input className="field" type="date" name="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><p className="text-sm muted">You pay this expense; it is split equally among all trip members.</p><button className="btn" disabled={saving}>{saving ? "Saving…" : "Save expense"}</button></form>;
}
